In [3]:
import pandas as pd;
import numpy as np;

In [6]:
s=pd.Series([1,3,23,6,10])
print(s)
print(f"The value at index 2 is {s[2]}")
print(s.index)

0     1
1     3
2    23
3     6
4    10
dtype: int64
The value at index 2 is 23
RangeIndex(start=0, stop=5, step=1)

In [8]:
named_series = pd.Series([19,10,30,17,15],index=["adam","eve","charlie","bob","messi"])
print(named_series["messi"])

print(named_series.values)
print(named_series.index)

15
[19 10 30 17 15]
Index(['adam', 'eve', 'charlie', 'bob', 'messi'], dtype='object')

In [10]:
#properties of series 
ser=pd.Series([1,4,5])

print(ser+10)
print(ser*10)

print(ser[ser>2])

0    11
1    14
2    15
dtype: int64
0    10
1    40
2    50
dtype: int64
1    4
2    5
dtype: int64

In [4]:
#----------------------------------------------------------------------------------------------
#datframes 
info = {
    "Name":["Adam","Eve","Bob"],
    "Marks":[90,98,91],
    "Grades":['B','A+','A']
}
df = pd.DataFrame(info)
print(df.columns)
print(df.index)

#df using lists and arrays 
arr= np.array([[10,20,30],[40,50,60],[70,80,90]])
df2 = pd.DataFrame(arr,columns=["m1","m2","m3"])
df2

lst = [[200,300,400],[500,600,700]]
df3= pd.DataFrame(lst,columns=["col1","col2","col3"])
df3

Index(['Name', 'Marks', 'Grades'], dtype='object')
RangeIndex(start=0, stop=3, step=1)

   col1  col2  col3
0   200   300   400
1   500   600   700

In [4]:
df= pd.read_csv("raw_data.csv")

In [37]:
df.head()
df.tail()
df.sample(2)
df.info()
df.describe()
df.nunique()
#sidhnt => df.sample(),df.info(),df.describe(),df.head(),df.nunique(),df.tail()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 6 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       11 non-null     int64
 1   name     10 non-null     object
 2   age      8 non-null      float64
 3   country  10 non-null     object
 4   gender   10 non-null     object
 5   income   10 non-null     float64
dtypes: float64(2), int64(1), object(3)
memory usage: 660.0+ bytes

id         10
name        9
age         6
country     6
gender      3
income      8
dtype: int64

In [16]:
df.dtypes
df.columns
df.shape
# cds => columns,dtypes and shape

(11, 6)

In [42]:
# df[["name","country"]]
df.loc[0:3]
df.loc[1,"age"]
df.iloc[:,[1,3]]

            name country
0       John Doe     USA
1       John Doe     USA
2     Jane Smith  Canada
3           Alex     USA
4   Maria Garcia   Spain
5         Li Wei   China
6            NaN   India
7     Ahmed Khan     NaN
8     Rachel Lee     USA
9    Carlos Ruiz  Mexico
10   Emily Davis     USA

In [57]:
#querying 
country_usa = df[df["country"]=="USA"]
# print(country_usa)

# print(country_usa[["age","gender"]])
cf = df[
    ((df["country"]=="USA") | (df["country"]=="Spain")) &
    (df["gender"]=="Female")
]
cf

#---------------------------------------------------------------
cnt = "USA"
df.query("age < 30 and country == @cnt and gender == 'Female' ")

   id        name   age country  gender   income
8   8  Rachel Lee  29.0     USA  Female  62000.0

In [71]:
#data cleaning 
df.isnull()
df.isnull().sum()
cdf= df.copy();

cdf["age"] = cdf["age"].fillna(cdf["age"].mean())
cdf

cdf["country"]= cdf["country"].ffill()
cdf

#duplicates 
df.duplicated()
df2= df.copy()
df.drop_duplicates(inplace=True)

In [74]:
df

    id          name   age country   gender   income
0    1      John Doe  29.0     USA     Male  55000.0
1    1      John Doe  29.0     USA     Male  55000.0
2    2    Jane Smith   NaN  Canada   Female  62000.0
3    3          Alex   NaN     USA  Unknown  47000.0
4    4  Maria Garcia  34.0   Spain   Female      NaN
5    5        Li Wei  27.0   China     Male  51000.0
6    6           NaN  45.0   India   Female  73000.0
7    7    Ahmed Khan  38.0     NaN     Male  68000.0
8    8    Rachel Lee  29.0     USA   Female  62000.0
9    9   Carlos Ruiz   NaN  Mexico     Male  45000.0
10  10   Emily Davis  31.0     USA      NaN  58000.0